In [2]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score,classification_report
import pickle

In [3]:
df = pd.read_csv('heart.csv')
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [4]:
df = pd.get_dummies(data=df,columns=['cp','restecg','thal','slope'])
df.columns

Index(['age', 'sex', 'trestbps', 'chol', 'fbs', 'thalach', 'exang', 'oldpeak',
       'ca', 'target', 'cp_0', 'cp_1', 'cp_2', 'cp_3', 'restecg_0',
       'restecg_1', 'restecg_2', 'thal_0', 'thal_1', 'thal_2', 'thal_3',
       'slope_0', 'slope_1', 'slope_2'],
      dtype='object')

In [5]:

x = df.drop(['target'], axis = 1)
y = df['target']
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 5)
cols = x_train.columns
feature_scaler = MinMaxScaler()
x_train = feature_scaler.fit_transform(x_train)
x_test = feature_scaler.transform(x_test)

In [22]:
radm_clf = RandomForestClassifier()
parameters = {'n_estimators': [150,175,200,225,250,300,325,350,375,400],'criterion': ['gini','entropy'],'max_features':['auto','sqrt','log2']}

clf = GridSearchCV(radm_clf, parameters, scoring='roc_auc' ,cv =5)
clf.fit(x_train, y_train)

clf.best_score_

0.87999777999778

In [23]:
clf.best_params_

{'criterion': 'gini', 'max_features': 'sqrt', 'n_estimators': 150}

In [24]:
model=RandomForestClassifier(criterion = 'gini',max_features = 'log2',n_estimators = 150)
model.fit(x_train,y_train)

RandomForestClassifier(max_features='log2', n_estimators=150)

In [25]:
x_train[2]

array([0.5106383 , 1.        , 0.36734694, 0.2739726 , 1.        ,
       0.74107143, 0.        , 0.        , 0.75      , 0.        ,
       0.        , 1.        , 0.        , 1.        , 0.        ,
       0.        , 0.        , 0.        , 1.        , 0.        ,
       0.        , 0.        , 1.        ])

In [33]:
pred=model.predict(x_test)
cr = classification_report(y_test, pred)
print(cr)

              precision    recall  f1-score   support

           0       0.90      0.90      0.90        30
           1       0.90      0.90      0.90        31

    accuracy                           0.90        61
   macro avg       0.90      0.90      0.90        61
weighted avg       0.90      0.90      0.90        61



In [35]:
pickle.dump(model, open('model.pkl','wb'))


In [6]:
model = pickle.load(open('heart-model.pkl','rb'))

In [12]:
print(len(x_train[2]))
print(x_train[2])
print(len(cols))
print(cols)

23
[0.5106383  1.         0.36734694 0.2739726  1.         0.74107143
 0.         0.         0.75       0.         0.         1.
 0.         1.         0.         0.         0.         0.
 1.         0.         0.         0.         1.        ]
23
Index(['age', 'sex', 'trestbps', 'chol', 'fbs', 'thalach', 'exang', 'oldpeak',
       'ca', 'cp_0', 'cp_1', 'cp_2', 'cp_3', 'restecg_0', 'restecg_1',
       'restecg_2', 'thal_0', 'thal_1', 'thal_2', 'thal_3', 'slope_0',
       'slope_1', 'slope_2'],
      dtype='object')


In [9]:
vals = [[56,1,132,245,1,1,188,1,4.5,1,0,0,1,0,0,1,0,1,0,0,1,0,0]]
print(len(vals[0]),len(cols))

23 23


In [10]:
model.predict(vals)

array([0], dtype=int64)

In [11]:
pred = model.predict_proba(vals)
pred

array([[0.7, 0.3]])